<a href="https://colab.research.google.com/github/Abdyrasul/tensorflow_scripts/blob/master/TensorflowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.13.0-rc2


In [0]:
hello = tf.constant("Hello ")
world = tf.constant("World")
with tf.Session() as sess:
  result = sess.run(hello+world)

In [6]:
print(result)

b'Hello World'


In [8]:
a = tf.constant(20)
b = tf.constant(10)

with tf.Session() as sess:
  result = sess.run(a+b)
print(result)

30


In [12]:
const = tf.constant(10)
fill_mat = tf.fill((4,4) , 10)
myzeros = tf.zeros((4,4))
myones = tf.ones((4,4))
myrandn = tf.random_normal((4,4), mean=0, stddev = 1.0)
myrandu = tf.random_uniform((4,4), minval=0,maxval=1)

my_ops = [const,fill_mat, myzeros,myones,myrandn,myrandu]
sess = tf.InteractiveSession()
for op in my_ops:
  print(sess.run(op))
  print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 1.1458247   1.4973329  -0.36557096 -0.23042147]
 [-0.5130656  -0.3058382   0.6274365   0.45197916]
 [ 0.6428634   0.6714652  -0.35690257 -1.9305389 ]
 [ 1.958415    0.0616704  -1.6073834  -0.4972214 ]]


[[0.4657538  0.45804572 0.6352804  0.28622985]
 [0.18399811 0.99190176 0.8166611  0.32118785]
 [0.72918785 0.7117171  0.36969352 0.09052157]
 [0.49133396 0.49217832 0.18672931 0.6237173 ]]




/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [13]:
a = tf.constant([[1,2],
                [3,4]])
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [14]:
b = tf.constant([[10],
               [100]])
result = tf.matmul(a,b)
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [15]:
result.eval()

array([[210],
       [430]], dtype=int32)